name = "matches-automation"
main = "worker.js"
compatibility_date = "2024-11-01"
workers_dev = true

[triggers]
crons = ["*/10 * * * *"]

[[kv_namespaces]]
binding = "MATCHES"
id = "e02bc61716794309a83cb21a457ded38"
preview_id = "e02bc61716794309a83cb21a457ded38"

[vars]
SCOREBAT_KEY = "YOUR_KEY"
RPC_URL = "YOUR_RPC_URL"
CONTRACT_ADDRESS = "0x..."
PRIVATE_KEY = "0x..."
